`throw` 문은 Javascript에서 예외 처리 메커니즘의 일부로 사용된다. 이 구문의 주요 목적은 현재 실행 중인 함수의 흐름을 중단하고 에러를 발생시키는 것이다. 그러나 `throw`는 **에러 객체뿐만 아니라 어떤 값이든 "던질(throw)" 수 있다.** 이러한 특성 때문에 `throw`는 다양한 방식으로 활용될 수 있다.

### 기본 사용법
```js
throw new Error("에러가 발생했습니다.");
```

기본 적으로 위와 같은 방식처럼 사용한다. 하지만 아래와 같은 방식으로 사용할 수 있다.
### 응용 사용법
```js
throw new "에러가 발생했습니다.";

throw new 404;

throw new { status: 404, message: "해당 정보를 찾을 수 없습니다."};
```
## 결론
`throw`는 에러를 발생시키는 것 이상으로 유연하게 사용할 수 있다. 비동기 처리나 `React` 의 `Suspense` 같은 경우에 작업의 상태에 따라 다양할 처리를 할 수 있도록 할 수 있다. 그러나 `throw`는 예외 처리 로직이 적절히 구성되어 있어야 하며, 이는 프로그램의 흐름을 이해하기 어렵게 만들 수 있으므로 주의해야 한다.